# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: Create and publish a Docker image

on:
  push:

env:
  IMAGE_PATH_AND_TAG: ghcr.io/application-repository:release-1.0
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1' 
  PORT: 3001
  COST_CENTER: "NO PROGRAM / 000000"
  STACK_NAME_PREFIX: application-repository
  CONTAINER_ENV: example

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        # https://github.com/marketplace/actions/aws-cdk-github-actions
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          working_dir: 'cdk'
        env:
          DOCKER_IMAGE: ${{ env.IMAGE_PATH_AND_TAG }}
 
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          working_dir: 'cdk'
          actions_comment: false
        env:
          DOCKER_IMAGE: ${{ env.IMAGE_PATH_AND_TAG }}
           